<?php
session_start();
if(!isset($_SESSION['status']))
	{
		header("location:exit.php");
	}
	require('fpdf/fpdf.php');
	include "bookMongerdb.php";
	$obj=new cDbase();	
	$res=$obj->sel("select * from student where RegNo like '".$_SESSION['uid']."' ");
	$row=mysql_fetch_array($res);
	
	//$content=$_POST['txtCont'];
	$ic=$_POST['txtIC'];
	$rc=$_POST['txtRC'];
	$lc=$_POST['txtLC'];
	$la=$_POST['txtLA'];
	$td=$_POST['txtd'];
	$sem=$_REQUEST['txtSem'];
	$rem=$_REQUEST['txtRem'];	
	$pdf=new FPDF();						//Create new pdf file
	$pdf->Open();   						//Open file
	$width=.2;
	$pdf->SetLineWidth($width);			//set line width
	$margin=.5;
	$pdf->SetRightMargin($margin);		//set right margin
	$pdf->AddPage();	
	$x_axis_initial = 50;					//Add first page   comment	/////////////////////
	$y_axis_initial = 25;				//set initial y axis position per page comment			///////////////////
	$pdf->SetFillColor(232, 232, 232);
	$pdf->SetFont('Arial', 'B', 20);
	$pdf->SetX(50);
	$pdf->SetY(35);
	$pdf->cell(55);
	$pdf->Cell(0,10,'Semester  Report Generation');
	$pdf->Cell(0,6, 'SEMESTER REPORT FOR THE SEMESTER '.$sem, 0, 1, 'L');
	$pdf->SetFont('Arial', 'B', 12);		//print date
	$pdf->SetY(55);
	$pdf->cell(30);
	//$pdf->Cell(0, 6, 'Date:'.date("Y-m-d"), 0, 0, 'L');
	$re=$content;
	$pdf->SetY(65);
	$pdf->cell(30);
	$pdf->Ln();
	$pdf->MultiCell(150,6,'', 0);
	$pdf->Ln(4);		
	$pdf->Cell(0, 6, 'BOOK MONGER', 0, 1, 'L');
	$pdf->AddPage();
	$pdf->SetY(75);
	$pdf->cell(35);
	$pdf->Cell(10, 6, 'Book bank report for the semester '.$sem.' of Batch. Rajagiri College. ', 0, 1, 'L');
	$pdf->Cell(10, 6,'The Details as follows',0,1,'L');	
	$pdf->Cell(10, 6,'Semester : '.$sem,0,1,'L');
	$pdf->Cell(10, 6,'Total number of books issued: '.$ic,0,1,'L');
	$pdf->Cell(10, 6,'Total Number of Books Returned : '.$rc,0,1,'L');
	$pdf->Cell(10, 6,'Number of Books Lost : '.$lc,0,1,'L');
	$pdf->Cell(10, 6,'Total amount received as fine : '.$la,0,1,'L');
	
	$pdf->Cell(10, 6,'Comments : '.$rem,0,1,'L');
	$pdf->AddPage();
	$pdf->Cell(10, 6,'Report Generated on : '.$td,0,1,'L');
	$pdf->Cell(10, 6,'Report Generated by : ',0,1,'L');
	$pdf->Cell(10, 6,'           Register Number : '.$_SESSION['uid'],0,1,'L');
	$pdf->Cell(10, 6,'           Name            : '.$row[1],0,1,'L');
	$pdf->Cell(10, 6,'           Semester Id     : '.$row[2],0,1,'L');
	
	$pdf->SetY(85);
	$pdf->cell(35);	
	//$pdf->Cell(80, 6, 'Date:', 0, 1, 'L');
	$pdf->Output ("./Reports/".$sem.'.pdf','F');
	header("location:samplerep.php");
?>
		
